spring:
  application:
    name: blog-backend
  datasource:
    url: jdbc:mysql://39.105.37.132:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 600000 # 单位ms
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true # JDK7之后所有的Connection都实现了AutoClosable
      filters: stat, wall
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        login-username: maxiao
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        allow:
        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"